### ISSUE TITLE
PlaceholderAPI skins

### ISSUE THREAD

**Issue by SladeHazard** [Pyrbu/ZNPCsPlus#108]
Hey, I'm trying to create leaderboard npcs with AjLeaderboards, does the plugin supports skins using placeholders? if not can this please be added: 

![image](https://github.com/Pyrbu/ZNPCsPlus/assets/45261094/eea62fff-193d-4f85-af80-b47d08fafff9)

**Comment by Pyrbu** [comment]
It does, you need to use a dynamic descriptor like this:
`/npc skin <id> dynamic <placeholder>`

You can also set it using the API by using the skin property and `SkinDescriptorFactory#createRefreshingDescriptor(String)`

However it is limited to only refreshing when the NPC respawns right now, which means it will only update whenever a player leaves the NPC's distance & re-enters

**Comment by SladeHazard** [comment]
ty

**Comment by SladeHazard** [comment]
Probably should add a exception catch for this.. as I can't really do anything about this error occuring when the placeholder doesn't have any valid data yet:


 [23:57:17 WARN]: [ZNPCsPlus Skin Cache] Failed to fetch skin from fallback server:
>
 [23:57:17 WARN]: java.io.IOException: Server returned HTTP response code: 400 for URL: https://api.ashcon.app/mojang/v2/user/
>
 [23:57:17 WARN]:       at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1939)
>
 [23:57:17 WARN]:       at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1525)
>
 [23:57:17 WARN]:       at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
>
 [23:57:17 WARN]:       at lol.pyr.znpcsplus.skin.cache.MojangSkinCache.lambda$fetchByNameFallback$1(MojangSkinCache.java:84)
>
 [23:57:17 WARN]:       at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
>
 [23:57:17 WARN]:       at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
>
 [23:57:17 WARN]:       at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
>
 [23:57:17 WARN]:       at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
>
 [23:57:17 WARN]:       at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
>
 [23:57:17 WARN]:       at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
>
 [23:57:17 WARN]:       at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by Pyrbu** [comment]
You can disable those warnings in the config
