### ISSUE TITLE
Folia 1.20.1 Error reported when closing server

### ISSUE THREAD

**Issue by nyancat-hu** [Pyrbu/ZNPCsPlus#117]
Error occurred (in the plugin loader) while disabling ZNPCsPlus v2.0.0-SNAPSHOT (Is it up to date?)
java.lang.IllegalStateException: Not scheduled yet
	at org.bukkit.scheduler.BukkitRunnable.checkScheduled(BukkitRunnable.java:156) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.scheduler.BukkitRunnable.getTaskId(BukkitRunnable.java:150) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.scheduler.BukkitRunnable.cancel(BukkitRunnable.java:30) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at lol.pyr.znpcsplus.ZNpcsPlus.onDisable(ZNpcsPlus.java:213) ~[[Z][NPC]ZNPCsPlus-2.0.0-SNAPSHOT.jar:?]
	at lol.pyr.znpcsplus.ZNpcsPlusBootstrap.onDisable(ZNpcsPlusBootstrap.java:80) ~[[Z][NPC]ZNPCsPlus-2.0.0-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[folia-1.20.1.jar:git-Folia-"b2306ae"]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:148) ~[folia-1.20.1.jar:git-Folia-"b2306ae"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:92) ~[folia-1.20.1.jar:git-Folia-"b2306ae"]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:528) ~[folia-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.disablePlugins(CraftServer.java:577) ~[folia-1.20.1.jar:git-Folia-"b2306ae"]
	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:1016) ~[folia-1.20.1.jar:git-Folia-"b2306ae"]
	at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:819) ~[folia-1.20.1.jar:git-Folia-"b2306ae"]
	at io.papermc.paper.threadedregions.RegionShutdownThread.run(RegionShutdownThread.java:136) ~[folia-1.20.1.jar:git-Folia-"b2306ae"]

**Comment by Pyrbu** [comment]
This has been fixed in the latest dev build
