### ISSUE TITLE
Error occurred while enabling ZNPCsPlus

### ISSUE THREAD

**Issue by Overwrite987** [Pyrbu/ZNPCsPlus#4]
I'm launching the plugin for the first time. there are no presets or any changes.

[19:11:10 ERROR]: Error occurred while enabling ZNPCsPlus v1.0.1 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at io.github.znetworkw.znpcservers.configuration.ConfigurationConstants.<clinit>(ConfigurationConstants.java:9) ~[ZNPCsPlus-1.0.1.jar:?]
        at lol.pyr.znpcsplus.ZNPCsPlus.onEnable(ZNPCsPlus.java:93) ~[ZNPCsPlus-1.0.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[plazma-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[plazma-1.19.4.jar:git-Plazma-"84f3148"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[plazma-1.19.4.jar:git-Plazma-"84f3148"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[plazma-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:569) ~[plazma-1.19.4.jar:git-Plazma-"84f3148"]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:480) ~[plazma-1.19.4.jar:git-Plazma-"84f3148"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:645) ~[plazma-1.19.4.jar:git-Plazma-"84f3148"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:444) ~[plazma-1.19.4.jar:git-Plazma-"84f3148"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:350) ~[plazma-1.19.4.jar:git-Plazma-"84f3148"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1122) ~[plazma-1.19.4.jar:git-Plazma-"84f3148"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[plazma-1.19.4.jar:git-Plazma-"84f3148"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.google.common.collect.ImmutableSet.stream()" because the return value of "java.util.Map.get(Object)" is null
        at io.github.znetworkw.znpcservers.configuration.Configuration.<init>(Configuration.java:40) ~[ZNPCsPlus-1.0.1.jar:?]
        at io.github.znetworkw.znpcservers.configuration.Configuration.<init>(Configuration.java:33) ~[ZNPCsPlus-1.0.1.jar:?]
        at io.github.znetworkw.znpcservers.configuration.Configuration.<clinit>(Configuration.java:28) ~[ZNPCsPlus-1.0.1.jar:?]
        ... 14 more

**Comment by Pyrbu** [comment]
Hi! Can you please post a copy of your configurations? I believe its a problem with those, you can also try booting it up with a fresh configuration and re-configure it to your liking

**Comment by Overwrite987** [comment]
> Hi! Can you please post a copy of your configurations? I believe its a problem with those, you can also try booting it up with a fresh configuration and re-configure it to your liking
but after all... the configuration is not even created.

**Comment by Pyrbu** [comment]
I see now, my friend helped me recreate the issue so I will get a patch out ASAP

**Comment by Pyrbu** [comment]
> > Hi! Can you please post a copy of your configurations? I believe its a problem with those, you can also try booting it up with a fresh configuration and re-configure it to your liking
> 
> but after all... the configuration is not even created.

The issue should now be resolved, please use the latest release
