### ISSUE TITLE
Random error after storage reload

### ISSUE THREAD

**Issue by Teslicek** [Pyrbu/ZNPCsPlus#74]
```[14:41:47 WARN]: [ZNPCsPlus] Plugin ZNPCsPlus v2.0.0-SNAPSHOT generated an exception while executing task 40
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1631) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at lol.pyr.znpcsplus.npc.NpcRegistryImpl.getProcessable(NpcRegistryImpl.java:94) ~[ZNPCsPlus #94.jar:?]
        at lol.pyr.znpcsplus.tasks.NpcProcessorTask.run(NpcProcessorTask.java:32) ~[ZNPCsPlus #94.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.20.1.jar:git-Pufferfish-14]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[pufferfish-1.20.1.jar:git-Pufferfish-14]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[pufferfish-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
Build #94

**Comment by D3v1s0m** [comment]
> ```
> java.util.ConcurrentModificationException: null
>         at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1631) ~[?:?]
>         at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
>         at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
>         at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
>         at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
>         at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
>         at lol.pyr.znpcsplus.npc.NpcRegistryImpl.getProcessable(NpcRegistryImpl.java:94) ~[ZNPCsPlus #94.jar:?]
>         at lol.pyr.znpcsplus.tasks.NpcProcessorTask.run(NpcProcessorTask.java:32) ~[ZNPCsPlus #94.jar:?]
>         at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.20.1.jar:git-Pufferfish-14]
>         at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[pufferfish-1.20.1.jar:git-Pufferfish-14]
>         at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[pufferfish-1.20.1.jar:?]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
>         at java.lang.Thread.run(Thread.java:833) ~[?:?]
> ```
> 
> 
>     
>   
> 
> Build #94

@Teslicek , can you please post the full error or logs

**Comment by Pyrbu** [comment]
This is most likely fixed
